package kiro

const (
	kiroFieldJSONRPC                   = "jsonrpc"
	kiroFieldMethod                    = "method"
	kiroFieldParams                    = "params"
	kiroFieldContent                   = "content"
	kiroFieldFunction                  = "function"
	kiroFieldFunctionCall              = "function_call"
	kiroFieldModel                     = "model"
	kiroFieldInput                     = "input"
	kiroFieldStream                    = "stream"
	kiroFieldStatus                    = "status"
	kiroFieldPhase                     = "phase"
	kiroFieldDetailsOmitted            = "details_omitted"
	kiroFieldMessage                   = "message"
	kiroFieldTitle                     = "title"
	kiroFieldUsage                     = "usage"
	kiroFieldMetadata                  = "metadata"
	kiroFieldOutputTokens              = "output_tokens"
	kiroFieldInputTokens               = "input_tokens"
	kiroFieldIndex                     = "index"
	kiroFieldDelta                     = "delta"
	kiroFieldStopReason                = "stop_reason"
	kiroFieldFinishReason              = "finish_reason"
	kiroFieldCreated                   = "created"
	kiroFieldChoices                   = "choices"
	kiroFieldResponseFormat            = "response_format"
	kiroFieldParallelToolCalls         = "parallel_tool_calls"
	kiroFieldTopP                      = "top_p"
	kiroFieldTemperature               = "temperature"
	kiroErrorInvalidRequest            = "invalid_request"
	kiroErrorUnsupportedResponseFormat = "unsupported_response_format"
	kiroStatusCompleted                = "completed"
	kiroStatusFailed                   = "failed"
	kiroStatusCancelled                = "cancelled"
	kiroStatusTruncated                = "truncated"
	kiroRoleAssistant                  = "assistant"
	kiroRoleSystem                     = "system"
)
