sonar.projectKey=godex-ci
sonar.projectName=godex
sonar.sources=cmd,internal
sonar.tests=cmd,internal
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go,**/testdata/**,bin/**,dist/**,target/**
sonar.go.coverage.reportPaths=target/sonar/coverage.out
sonar.qualitygate.wait=true
